### ISSUE TITLE
NOT_HEATING_GROUP - while setting temperature values

### ISSUE THREAD

**Issue by ToTXR4Y** [iobroker-community-adapters/ioBroker.hmip#310] opened 2021-11-20 08:48 UTC
`<html><body>

hmip.0 | 2330 | 2021-11-20 09:24:16.519 | warn | Request error: StatusCodeError: 400 - {"errorCode":"NOT_HEATING_GROUP"}
-- | -- | -- | -- | --
hmip.0 | 2330 | 2021-11-20 09:23:44.607 | warn | Request error: StatusCodeError: 400 - {"errorCode":"NOT_HEATING_GROUP"}

</body>
</html>`

This happens to me while opening a window (not using HM sensors) and running a iobroker script to set a specified temperature value. I am using wall-thermostats with the heater-drivers. Is there a workaround to suppress this warning or do i have to edit some of my scripts?

**Comment by Apollon77** [comment] 2021-11-29 22:01
Please set adapter to debug log, provide the full log from start and force this issue. Post the log please. Get the Log frpom logfile on disk in /opt/iobroker/logs/... and not from admin

**Comment by ToTXR4Y** [comment] 2021-11-30 21:03
2021-11-30 21:58:25.716  - [32minfo[39m: host.iobroker stopInstance system.adapter.hmip.0 (force=false, process=true)
2021-11-30 21:58:25.738  - [32minfo[39m: host.iobroker stopInstance system.adapter.hmip.0 send kill signal
2021-11-30 21:58:25.739  - [32minfo[39m: hmip.0 (343506) Got terminate signal TERMINATE_YOURSELF
2021-11-30 21:58:25.750  - [32minfo[39m: hmip.0 (343506) cleaned everything up...
2021-11-30 21:58:25.751  - [32minfo[39m: hmip.0 (343506) terminating
2021-11-30 21:58:25.753  - [32minfo[39m: hmip.0 (343506) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2021-11-30 21:58:26.633  - [32minfo[39m: host.iobroker instance system.adapter.hmip.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2021-11-30 21:58:29.010  - [32minfo[39m: host.iobroker instance system.adapter.hmip.0 started with pid 427254
2021-11-30 21:58:30.573  - [34mdebug[39m: hmip.0 (427254) Redis Objects: Use Redis connection: 127.0.0.1:9001
2021-11-30 21:58:30.621  - [34mdebug[39m: hmip.0 (427254) Objects client ready ... initialize now
2021-11-30 21:58:30.624  - [34mdebug[39m: hmip.0 (427254) Objects create System PubSub Client
2021-11-30 21:58:30.626  - [34mdebug[39m: hmip.0 (427254) Objects create User PubSub Client
2021-11-30 21:58:30.627  - [34mdebug[39m: hmip.0 (427254) Objects client initialize lua scripts
2021-11-30 21:58:31.101  - [34mdebug[39m: hmip.0 (427254) Objects connected to redis: 127.0.0.1:9001
2021-11-30 21:58:31.121  - [34mdebug[39m: hmip.0 (427254) objectDB connected
2021-11-30 21:58:31.132  - [34mdebug[39m: hmip.0 (427254) Redis States: Use Redis connection: 127.0.0.1:9000
2021-11-30 21:58:31.376  - [34mdebug[39m: hmip.0 (427254) States create System PubSub Client
2021-11-30 21:58:31.377  - [34mdebug[39m: hmip.0 (427254) States create User PubSub Client
2021-11-30 21:58:31.526  - [34mdebug[39m: hmip.0 (427254) States connected to redis: 127.0.0.1:9000
2021-11-30 21:58:31.528  - [34mdebug[39m: hmip.0 (427254) statesDB connected
2021-11-30 21:58:32.335  - [34mdebug[39m: hmip.0 (427254) Plugin sentry Initialize Plugin (enabled=true)
2021-11-30 21:58:32.661  - [32minfo[39m: hmip.0 (427254) starting. Version 1.14.0 in /opt/iobroker/node_modules/iobroker.hmip, node: v14.18.1, js-controller: 3.3.20
2021-11-30 21:58:32.701  - [34mdebug[39m: hmip.0 (427254) ready
2021-11-30 21:58:33.507  - [34mdebug[39m: hmip.0 (427254) createObjectsForDevices
2021-11-30 21:58:34.927  - [34mdebug[39m: hmip.0 (427254) createObjectsForGroups
2021-11-30 21:58:37.927  - [34mdebug[39m: hmip.0 (427254) createObjectsForClients
2021-11-30 21:58:38.067  - [34mdebug[39m: hmip.0 (427254) createObjectsForHomes
2021-11-30 21:58:38.271  - [34mdebug[39m: hmip.0 (427254) connectWebsocket
2021-11-30 21:58:38.278  - [34mdebug[39m: hmip.0 (427254) updateDeviceStates
2021-11-30 21:58:38.426  - [32minfo[39m: hmip.0 (427254) ws connection opened
2021-11-30 21:58:40.543  - [34mdebug[39m: hmip.0 (427254) subscribeStates
2021-11-30 21:58:40.544  - [32minfo[39m: hmip.0 (427254) hmip adapter connected and ready
2021-11-30 21:58:49.698  - [34mdebug[39m: hmip.0 (427254) state change - setPointTemperature - id 1434c972-f05f-475e-94a7-608c0bb909fe,8d9c910a-0a33-4c30-8e68-89607a19ed30 - value rounded to 16 (step=0.5 )
2021-11-30 21:58:54.700  - [34mdebug[39m: hmip.0 (427254) setPointTemperature - id 1434c972-f05f-475e-94a7-608c0bb909fe,8d9c910a-0a33-4c30-8e68-89607a19ed30 - Send debounced value 16 now to HMIP
2021-11-30 21:58:54.929  - [33mwarn[39m: hmip.0 (427254) Request error: StatusCodeError: 400 - {"errorCode":"NOT_HEATING_GROUP"}
2021-11-30 21:59:01.102  - [34mdebug[39m: hmip.0 (427254) state change - setPointTemperature - id 1434c972-f05f-475e-94a7-608c0bb909fe,8d9c910a-0a33-4c30-8e68-89607a19ed30 - value rounded to 22 (step=0.5 )
2021-11-30 21:59:06.103  - [34mdebug[39m: hmip.0 (427254) setPointTemperature - id 1434c972-f05f-475e-94a7-608c0bb909fe,8d9c910a-0a33-4c30-8e68-89607a19ed30 - Send debounced value 22 now to HMIP
2021-11-30 21:59:06.335  - [33mwarn[39m: hmip.0 (427254) Request error: StatusCodeError: 400 - {"errorCode":"NOT_HEATING_GROUP"}

**Comment by Apollon77** [comment] 2021-11-30 21:41
Is this really all logs?= I miss some longer json lines with the real data. In fcat ... are the devices setup correctly and assigned to a heating group and sich? Can you control them via the app?

**Comment by ToTXR4Y** [comment] 2021-12-02 19:56
Thats the log i pulled from disc through sftp. Devices are fully functional, the temperature is set correctly but the warning appears everytime i open a window. The window is attached through zigbee xiaomi reed-contact and a js-script is triggered to set HMIP thermal to specified values.

**Comment by Apollon77** [comment] 2022-01-01 21:50
And you can successfully set the temperature via the HMIP app? For me it seems that the device is somehow not in ay heating group and temperatures can only be sent for heating groups from what I know ... Can you please check that?

And please show me the object definition of the relevant state that you set -  Admin - Objects - klick the pencil icon in the line and post the JSON from "Object data". 

It seems that there is a place where the group devices are not send as array but as string ... Lets try to find the reason.

**Comment by ToTXR4Y** [comment] 2022-01-02 01:46
Yes, through the app it is possible to set the temperature. You can not define a heating group within the app, if you´re not using any window-contacts or such stuff. The temperature itself is correctly set for the targeted device, but it throws the warning.

---
JSON:
{
  "type": "state",
  "common": {
    "name": "setPointTemperature",
    "type": "number",
    "role": "level.temperature",
    "unit": "°C",
    "read": true,
    "write": true,
    "smartName": {
      "smartType": "THERMOSTAT"
    }
  },
  "native": {
    "id": [
      "1434c972-f05f-475e-94a7-608c0bb909fe"
    ],
    "parameter": "setPointTemperature",
    "step": 0.5,
    "debounce": 5000
  },
  "from": "system.adapter.hmip.0",
  "user": "system.user.admin",
  "ts": 1640798520036,
  "_id": "hmip.0.devices.3014F711A000201BE997940C.channels.1.setPointTemperature",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

**Comment by Apollon77** [comment] 2022-01-02 07:48
Aaahhhhh so it works you just get this warning?? Good to know. But formally the api is returning exactly the error. So I have no idea how to decide when such an error is relevant and when not ...hm ...

**Comment by Apollon77** [comment] 2022-01-02 07:49
But also your log you posted do not really match to what I see in the object ... is the log still exactly as last time??

**Comment by ToTXR4Y** [comment] 2022-01-02 20:37
It happens on all of my thermostats. Yes, log is the same.

**Comment by Apollon77** [comment] 2022-01-02 21:11
Thej please send a silly loglevel log including sich an setTemperature action

**Comment by RP70DP** [comment] 2022-01-05 15:46
I've tried to reproduce the error. I didn't succeed. Here is my log:
```
2022-01-05 16:23:38.637  - [32minfo[39m: hmip.0 (8558) hmip adapter connected and ready
2022-01-05 16:23:54.283  - [34mdebug[39m: hmip.0 (8558) state change - setPointTemperature - id ["bf2a5dd6-5bd8-4dbc-ac69-13f67ce2e09f"] - value rounded to 18.5 (step=0.5 )
2022-01-05 16:23:59.285  - [34mdebug[39m: hmip.0 (8558) setPointTemperature - id ["bf2a5dd6-5bd8-4dbc-ac69-13f67ce2e09f"] - Send debounced value 18.5 now to HMIP
2022-01-05 16:24:31.885  - [34mdebug[39m: hmip.0 (8558) state change - setPointTemperature - id ["bf2a5dd6-5bd8-4dbc-ac69-13f67ce2e09f"] - value rounded to 17.5 (step=0.5 )
2022-01-05 16:24:36.887  - [34mdebug[39m: hmip.0 (8558) setPointTemperature - id ["bf2a5dd6-5bd8-4dbc-ac69-13f67ce2e09f"] - Send debounced value 17.5 now to HMIP
2022-01-05 16:25:46.212  - [34mdebug[39m: hmip.0 (8558) state change - setPointTemperature - id ["bf2a5dd6-5bd8-4dbc-ac69-13f67ce2e09f"] - value rounded to 18.5 (step=0.5 )
2022-01-05 16:25:51.213  - [34mdebug[39m: hmip.0 (8558) setPointTemperature - id ["bf2a5dd6-5bd8-4dbc-ac69-13f67ce2e09f"] - Send debounced value 18.5 now to HMIP
2022-01-05 16:33:07.443  - [34mdebug[39m: hmip.0 (8558) state change - setPointTemperature - id ["bf2a5dd6-5bd8-4dbc-ac69-13f67ce2e09f"] - value rounded to 17.5 (step=0.5 )
2022-01-05 16:33:12.444  - [34mdebug[39m: hmip.0 (8558) setPointTemperature - id ["bf2a5dd6-5bd8-4dbc-ac69-13f67ce2e09f"] - Send debounced value 17.5 now to HMIP
2022-01-05 16:33:56.317  - [34mdebug[39m: hmip.0 (8558) state change - setPointTemperature - id ["bf2a5dd6-5bd8-4dbc-ac69-13f67ce2e09f"] - value rounded to 18.5 (step=0.5 )
2022-01-05 16:34:01.318  - [34mdebug[39m: hmip.0 (8558) setPointTemperature - id ["bf2a5dd6-5bd8-4dbc-ac69-13f67ce2e09f"] - Send debounced value 18.5 now to HMIP
```
What you can see is that no matter what value i changed (valve, wall thermostat, heating group), the log is always the same.
I never saw such a long id (1434c972-f05f-475e-94a7-608c0bb909fe,8d9c910a-0a33-4c30-8e68-89607a19ed30).

**Comment by Apollon77** [comment] 2022-01-05 15:59
@RP70DP Thank you for your confirmation ... exactly that way the log needs to look like and then it also works ...

Also the object that was posted do not map to thelog messge (or better: with this object the log should never be that way) ... this is very mysterious

@ToTXR4Y please try to remove the istance and also uninstall the adapter and try a fresh start with the adapter

**Comment by RP70DP** [comment] 2022-01-05 16:24
@Apollon77 
You're welcome.

Another log with an independent valve (no wall thermostat, no shutter contact):
```
2022-01-05 17:18:07.357  - [34mdebug[39m: hmip.1 (11012) state change - setPointTemperature - id ["d9f51315-1e41-4be5-b57c-273949421379"] - value rounded to 18 (step=0.5 )
2022-01-05 17:18:12.359  - [34mdebug[39m: hmip.1 (11012) setPointTemperature - id ["d9f51315-1e41-4be5-b57c-273949421379"] - Send debounced value 18 now to HMIP
```
It's the same.

**Comment by ToTXR4Y** [comment] 2022-01-05 16:41
> @RP70DP Thank you for your confirmation ... exactly that way the log needs to look like and then it also works ...
> 
> Also the object that was posted do not map to thelog messge (or better: with this object the log should never be that way) ... this is very mysterious
> 
> @ToTXR4Y please try to remove the istance and also uninstall the adapter and try a fresh start with the adapter

I´ve deleted the old adapter and did a fresh start after restarting ioBroker. Error is the same. I included the silly log (attention, it is rather long...). It doesn´t matter if i set the valve setPointTemperature or the connected wall Thermostat to set the temp. Error is on both object the same.

Log:
<html><body>


2022-01-05 17:28:19.558  - debug: hmip.0 (1818640) subscribeStates
--
2022-01-05 17:28:19.559  - info: hmip.0 (1818640) hmip adapter connected and ready
2022-01-05 17:28:37.701  - silly:  hmip.0 (1818640) States user redis pmessage  hmip.0.*/hmip.0.devices.3014F711A000265BE989ABAA.channels.1.setPointTemperature:{"val":16,"ack":false,"ts":1641400117691,"q":0,"c":"script.js.common.Heizung.Heizung_Schlafzimmer","from":"system.adapter.javascript.0","user":"system.user.admin","lc":1641400117691}
2022-01-05 17:28:37.709  - debug:  hmip.0 (1818640) state change - setPointTemperature - id  ["1434c972-f05f-475e-94a7-608c0bb909fe","8d9c910a-0a33-4c30-8e68-89607a19ed30"]  - value rounded to 16 (step=0.5 )
2022-01-05 17:28:42.711  - debug:  hmip.0 (1818640) setPointTemperature - id  ["1434c972-f05f-475e-94a7-608c0bb909fe","8d9c910a-0a33-4c30-8e68-89607a19ed30"]  - Send debounced value 16 now to HMIP
2022-01-05 17:28:42.836  - silly:  hmip.0 (1818640) _updateGroupStates -  {"id":"1434c972-f05f-475e-94a7-608c0bb909fe","homeId":"39227166-26f1-4696-bba9-ffdd6400b1cd","metaGroupId":"e7246a0a-4745-4b67-ac4a-5b2a79fb97bc","label":"SCHLAFZIMMER","lastStatusUpdate":1641400015303,"unreach":false,"lowBat":false,"dutyCycle":false,"type":"HEATING","channels":[{"deviceId":"3014F711A000265BE989ABAA","channelIndex":1},{"deviceId":"3014F711A000201BE997940C","channelIndex":1}],"windowOpenTemperature":12,"setPointTemperature":16,"minTemperature":5,"maxTemperature":30,"windowState":null,"cooling":false,"partyMode":false,"controlMode":"AUTOMATIC","profiles":{"PROFILE_3":{"profileId":"7381874b-612a-4ff6-b027-d65367c895bc","groupId":"1434c972-f05f-475e-94a7-608c0bb909fe","index":"PROFILE_3","name":"","visible":false,"enabled":true},"PROFILE_4":{"profileId":"b3d05933-9c6b-4451-a0b2-f9171083f3dc","groupId":"1434c972-f05f-475e-94a7-608c0bb909fe","index":"PROFILE_4","name":"","visible":true,"enabled":true},"PROFILE_5":{"profileId":"a7ceac4c-dd98-4bb4-964a-c2b4a799780d","groupId":"1434c972-f05f-475e-94a7-608c0bb909fe","index":"PROFILE_5","name":"","visible":true,"enabled":true},"PROFILE_1":{"profileId":"da972fb6-b9c6-4833-bc3e-6674a8deae5e","groupId":"1434c972-f05f-475e-94a7-608c0bb909fe","index":"PROFILE_1","name":"","visible":true,"enabled":true},"PROFILE_6":{"profileId":"55186d49-f2f7-431f-ad0a-f3ee84e8b090","groupId":"1434c972-f05f-475e-94a7-608c0bb909fe","index":"PROFILE_6","name":"","visible":false,"enabled":true},"PROFILE_2":{"profileId":"9161b687-f80d-4a06-b9e9-5e97f462cff1","groupId":"1434c972-f05f-475e-94a7-608c0bb909fe","index":"PROFILE_2","name":"","visible":true,"enabled":true}},"activeProfile":"PROFILE_1","boostMode":false,"boostDuration":5,"actualTemperature":22.6,"humidity":58,"coolingAllowed":false,"coolingIgnored":false,"ecoAllowed":true,"ecoIgnored":false,"controllable":true,"boostAllowed":true,"floorHeatingMode":"FLOOR_HEATING_STANDARD","humidityLimitEnabled":true,"humidityLimitValue":60,"externalClockEnabled":false,"externalClockHeatingTemperature":19,"externalClockCoolingTemperature":23,"valvePosition":0,"sabotage":null,"valveSilentModeSupported":false,"valveSilentModeEnabled":false,"lastSetPointReachedTimestamp":1641400015303,"lastSetPointUpdatedTimestamp":1641400015303,"heatingFailureSupported":true}
2022-01-05 17:28:42.868  - silly:  hmip.0 (1818640) States user redis pmessage  hmip.0.*/hmip.0.groups.1434c972-f05f-475e-94a7-608c0bb909fe.info.type:{"val":"HEATING","ack":true,"ts":1641400122862,"q":0,"from":"system.adapter.hmip.0","user":"system.user.admin","lc":1641399705029}
2022-01-05 17:28:42.872  - silly:  hmip.0 (1818640) States user redis pmessage  hmip.0.*/hmip.0.groups.1434c972-f05f-475e-94a7-608c0bb909fe.info.label:{"val":"SCHLAFZIMMER","ack":true,"ts":1641400122862,"q":0,"from":"system.adapter.hmip.0","user":"system.user.admin","lc":1641399705029}
2022-01-05 17:28:42.880  - silly:  hmip.0 (1818640) States user redis pmessage  hmip.0.*/hmip.0.groups.1434c972-f05f-475e-94a7-608c0bb909fe.windowOpenTemperature:{"val":12,"ack":true,"ts":1641400122862,"q":0,"from":"system.adapter.hmip.0","user":"system.user.admin","lc":1641399705029}
2022-01-05 17:28:42.884  - silly:  hmip.0 (1818640) States user redis pmessage  hmip.0.*/hmip.0.groups.1434c972-f05f-475e-94a7-608c0bb909fe.setPointTemperature:{"val":16,"ack":true,"ts":1641400122862,"q":0,"from":"system.adapter.hmip.0","user":"system.user.admin","lc":1641400122862}
2022-01-05 17:28:42.887  - silly:  hmip.0 (1818640) States user redis pmessage  hmip.0.*/hmip.0.groups.1434c972-f05f-475e-94a7-608c0bb909fe.minTemperature:{"val":5,"ack":true,"ts":1641400122863,"q":0,"from":"system.adapter.hmip.0","user":"system.user.admin","lc":1641399705029}
2022-01-05 17:28:42.900  - silly:  hmip.0 (1818640) States user redis pmessage  hmip.0.*/hmip.0.groups.1434c972-f05f-475e-94a7-608c0bb909fe.maxTemperature:{"val":30,"ack":true,"ts":1641400122863,"q":0,"from":"system.adapter.hmip.0","user":"system.user.admin","lc":1641399705029}
2022-01-05 17:28:42.902  - silly:  hmip.0 (1818640) States user redis pmessage  hmip.0.*/hmip.0.groups.1434c972-f05f-475e-94a7-608c0bb909fe.windowState:{"val":null,"ack":true,"ts":1641400122866,"q":0,"from":"system.adapter.hmip.0","user":"system.user.admin","lc":1641399705029}
2022-01-05 17:28:42.909  - silly:  hmip.0 (1818640) States user redis pmessage  hmip.0.*/hmip.0.groups.1434c972-f05f-475e-94a7-608c0bb909fe.cooling:{"val":false,"ack":true,"ts":1641400122866,"q":0,"from":"system.adapter.hmip.0","user":"system.user.admin","lc":1641399705029}
2022-01-05 17:28:42.910  - silly:  hmip.0 (1818640) States user redis pmessage  hmip.0.*/hmip.0.groups.1434c972-f05f-475e-94a7-608c0bb909fe.partyMode:{"val":false,"ack":true,"ts":1641400122866,"q":0,"from":"system.adapter.hmip.0","user":"system.user.admin","lc":1641399705029}
2022-01-05 17:28:42.912  - silly:  hmip.0 (1818640) States user redis pmessage  hmip.0.*/hmip.0.groups.1434c972-f05f-475e-94a7-608c0bb909fe.controlMode:{"val":"AUTOMATIC","ack":true,"ts":1641400122866,"q":0,"from":"system.adapter.hmip.0","user":"system.user.admin","lc":1641399705030}
2022-01-05 17:28:42.913  - silly:  hmip.0 (1818640) States user redis pmessage  hmip.0.*/hmip.0.groups.1434c972-f05f-475e-94a7-608c0bb909fe.activeProfile:{"val":"PROFILE_1","ack":true,"ts":1641400122866,"q":0,"from":"system.adapter.hmip.0","user":"system.user.admin","lc":1641399705030}
2022-01-05 17:28:42.915  - silly:  hmip.0 (1818640) States user redis pmessage  hmip.0.*/hmip.0.groups.1434c972-f05f-475e-94a7-608c0bb909fe.boostMode:{"val":false,"ack":true,"ts":1641400122867,"q":0,"from":"system.adapter.hmip.0","user":"system.user.admin","lc":1641399705030}
2022-01-05 17:28:42.939  - silly:  hmip.0 (1818640) States user redis pmessage  hmip.0.*/hmip.0.groups.1434c972-f05f-475e-94a7-608c0bb909fe.boostDuration:{"val":5,"ack":true,"ts":1641400122867,"q":0,"from":"system.adapter.hmip.0","user":"system.user.admin","lc":1641399705030}
2022-01-05 17:28:42.951  - silly:  hmip.0 (1818640) States user redis pmessage  hmip.0.*/hmip.0.groups.1434c972-f05f-475e-94a7-608c0bb909fe.actualTemperature:{"val":22.6,"ack":true,"ts":1641400122891,"q":0,"from":"system.adapter.hmip.0","user":"system.user.admin","lc":1641399705051}
2022-01-05 17:28:42.970  - silly:  hmip.0 (1818640) States user redis pmessage  hmip.0.*/hmip.0.groups.1434c972-f05f-475e-94a7-608c0bb909fe.humidity:{"val":58,"ack":true,"ts":1641400122891,"q":0,"from":"system.adapter.hmip.0","user":"system.user.admin","lc":1641399705055}
2022-01-05 17:28:42.974  - silly:  hmip.0 (1818640) States user redis pmessage  hmip.0.*/hmip.0.groups.1434c972-f05f-475e-94a7-608c0bb909fe.coolingAllowed:{"val":false,"ack":true,"ts":1641400122892,"q":0,"from":"system.adapter.hmip.0","user":"system.user.admin","lc":1641399705056}
2022-01-05 17:28:42.975  - silly:  hmip.0 (1818640) States user redis pmessage  hmip.0.*/hmip.0.groups.1434c972-f05f-475e-94a7-608c0bb909fe.coolingIgnored:{"val":false,"ack":true,"ts":1641400122892,"q":0,"from":"system.adapter.hmip.0","user":"system.user.admin","lc":1641399705057}
2022-01-05 17:28:42.987  - warn: hmip.0 (1818640) Request error: StatusCodeError: 400 - {"errorCode":"NOT_HEATING_GROUP"}
2022-01-05 17:28:42.989  - silly:  hmip.0 (1818640) States user redis pmessage  hmip.0.*/hmip.0.groups.1434c972-f05f-475e-94a7-608c0bb909fe.ecoAllowed:{"val":true,"ack":true,"ts":1641400122892,"q":0,"from":"system.adapter.hmip.0","user":"system.user.admin","lc":1641399705057}
2022-01-05 17:28:43.024  - silly:  hmip.0 (1818640) States user redis pmessage  hmip.0.*/hmip.0.groups.1434c972-f05f-475e-94a7-608c0bb909fe.ecoIgnored:{"val":false,"ack":true,"ts":1641400122892,"q":0,"from":"system.adapter.hmip.0","user":"system.user.admin","lc":1641399705057}
2022-01-05 17:28:43.025  - silly:  hmip.0 (1818640) States user redis pmessage  hmip.0.*/hmip.0.groups.1434c972-f05f-475e-94a7-608c0bb909fe.controllable:{"val":true,"ack":true,"ts":1641400122893,"q":0,"from":"system.adapter.hmip.0","user":"system.user.admin","lc":1641399705057}
2022-01-05 17:28:43.026  - silly:  hmip.0 (1818640) States user redis pmessage  hmip.0.*/hmip.0.groups.1434c972-f05f-475e-94a7-608c0bb909fe.floorHeatingMode:{"val":"FLOOR_HEATING_STANDARD","ack":true,"ts":1641400122894,"q":0,"from":"system.adapter.hmip.0","user":"system.user.admin","lc":1641399705057}
2022-01-05 17:28:43.026  - silly:  hmip.0 (1818640) States user redis pmessage  hmip.0.*/hmip.0.groups.1434c972-f05f-475e-94a7-608c0bb909fe.humidityLimitEnabled:{"val":true,"ack":true,"ts":1641400122894,"q":0,"from":"system.adapter.hmip.0","user":"system.user.admin","lc":1641399705059}
2022-01-05 17:28:43.027  - silly:  hmip.0 (1818640) States user redis pmessage  hmip.0.*/hmip.0.groups.1434c972-f05f-475e-94a7-608c0bb909fe.humidityLimitValue:{"val":60,"ack":true,"ts":1641400122894,"q":0,"from":"system.adapter.hmip.0","user":"system.user.admin","lc":1641399705059}
2022-01-05 17:28:43.027  - silly:  hmip.0 (1818640) States user redis pmessage  hmip.0.*/hmip.0.groups.1434c972-f05f-475e-94a7-608c0bb909fe.externalClockEnabled:{"val":false,"ack":true,"ts":1641400122894,"q":0,"from":"system.adapter.hmip.0","user":"system.user.admin","lc":1641399705059}
2022-01-05 17:28:43.028  - silly:  hmip.0 (1818640) States user redis pmessage  hmip.0.*/hmip.0.groups.1434c972-f05f-475e-94a7-608c0bb909fe.externalClockHeatingTemperature:{"val":19,"ack":true,"ts":1641400122896,"q":0,"from":"system.adapter.hmip.0","user":"system.user.admin","lc":1641399705061}
2022-01-05 17:28:43.029  - silly:  hmip.0 (1818640) States user redis pmessage  hmip.0.*/hmip.0.groups.1434c972-f05f-475e-94a7-608c0bb909fe.externalClockCoolingTemperature:{"val":23,"ack":true,"ts":1641400122896,"q":0,"from":"system.adapter.hmip.0","user":"system.user.admin","lc":1641399705061}
2022-01-05 17:28:43.029  - silly:  hmip.0 (1818640) States user redis pmessage  hmip.0.*/hmip.0.groups.1434c972-f05f-475e-94a7-608c0bb909fe.valvePosition:{"val":0,"ack":true,"ts":1641400122896,"q":0,"from":"system.adapter.hmip.0","user":"system.user.admin","lc":1641399705061}
2022-01-05 17:28:43.030  - silly:  hmip.0 (1818640) States user redis pmessage  hmip.0.*/hmip.0.groups.1434c972-f05f-475e-94a7-608c0bb909fe.sabotage:{"val":null,"ack":true,"ts":1641400122896,"q":0,"from":"system.adapter.hmip.0","user":"system.user.admin","lc":1641399705061}
2022-01-05 17:28:44.383  - silly:  hmip.0 (1818640) updateDeviceStates -  WALL_MOUNTED_THERMOSTAT_BASIC_HUMIDITY -  {"id":"3014F711A000265BE989ABAA","homeId":"39227166-26f1-4696-bba9-ffdd6400b1cd","label":"Wandthermostat","lastStatusUpdate":1641400124358,"type":"WALL_MOUNTED_THERMOSTAT_BASIC_HUMIDITY","functionalChannels":{"0":{"label":"","deviceId":"3014F711A000265BE989ABAA","index":0,"groupIndex":0,"functionalChannelType":"DEVICE_OPERATIONLOCK","groups":["e7246a0a-4745-4b67-ac4a-5b2a79fb97bc"],"unreach":false,"lowBat":false,"routerModuleEnabled":false,"multicastRoutingEnabled":false,"routerModuleSupported":false,"rssiDeviceValue":-47,"rssiPeerValue":-51,"configPending":false,"dutyCycle":false,"deviceOverloaded":false,"coProUpdateFailure":false,"coProFaulty":false,"coProRestartNeeded":false,"deviceUndervoltage":false,"deviceOverheated":false,"temperatureOutOfRange":false,"devicePowerFailureDetected":false,"supportedOptionalFeatures":{"IFeatureDeviceParticulateMatterSensorCommunicationError":false,"IFeatureDeviceCoProRestart":false,"IFeatureDeviceOverheated":false,"IOptionalFeatureDutyCycle":true,"IOptionalFeatureDeviceErrorLockJammed":false,"IFeatureMulticastRouter":false,"IFeatureProfilePeriodLimit":false,"IFeatureDeviceCoProUpdate":false,"IFeaturePowerShortCircuit":false,"IFeatureDevicePowerFailure":false,"IFeatureDeviceTemperatureHumiditySensorCommunicationError":false,"IFeatureShortCircuitDataLine":false,"IFeatureRssiValue":true,"IFeatureBusConfigMismatch":false,"IFeatureDeviceUndervoltage":false,"IFeatureDeviceParticulateMatterSensorError":false,"IFeatureDeviceOverloaded":false,"IFeatureDeviceCoProError":false,"IOptionalFeatureDisplayContrast":false,"IFeatureDeviceIdentify":false,"IOptionalFeatureLowBat":true,"IOptionalFeatureMountingOrientation":false,"IFeatureDeviceTemperatureHumiditySensorError":false,"IFeatureDeviceTemperatureOutOfRange":false},"busConfigMismatch":null,"powerShortCircuit":null,"shortCircuitDataLine":null,"profilePeriodLimitReached":null,"mountingOrientation":null,"temperatureHumiditySensorError":null,"temperatureHumiditySensorCommunicationError":null,"particulateMatterSensorError":null,"particulateMatterSensorCommunicationError":null,"displayContrast":null,"lockJammed":null,"operationLockActive":false},"1":{"label":"","deviceId":"3014F711A000265BE989ABAA","index":1,"groupIndex":1,"functionalChannelType":"WALL_MOUNTED_THERMOSTAT_PRO_CHANNEL","groups":["1434c972-f05f-475e-94a7-608c0bb909fe","8d9c910a-0a33-4c30-8e68-89607a19ed30"],"temperatureOffset":0,"actualTemperature":22.7,"setPointTemperature":16,"display":"ACTUAL_HUMIDITY","humidity":59,"vaporAmount":11.892310445919296}},"manufacturerCode":1,"oem":"eQ-3","liveUpdateState":"UP_TO_DATE","firmwareVersion":"1.0.12","firmwareVersionInteger":65548,"availableFirmwareVersion":"0.0.0","serializedGlobalTradeItemNumber":"3014F711A000265BE989ABAA","modelType":"HmIP-WTH-B","modelId":408,"permanentlyReachable":true,"connectionType":"HMIP_RF","updateState":"BACKGROUND_UPDATE_NOT_SUPPORTED"}


</body>
</html>

**Comment by Apollon77** [comment] 2022-01-05 19:46
Ok, please show the object hmip.0.devices.3014F711A000265BE989ABAA.channels.1.setPointTemperature

The following happens: Somehow this thermostat is assigned in two groups (internally). Thats why the adapter sends the temperatire info to both of them. The first (1434c972-f05f-475e-94a7-608c0bb909fe) is send and also confirmed ... the second one createds this error.

**Comment by RP70DP** [comment] 2022-01-05 20:04
Unjoin the device and join again.

**Comment by ToTXR4Y** [comment] 2022-01-06 18:43
Objekt-Details from this one. It has two attached IDs in the object details. It is connected to the wall-thermostat, that´s why it is in an internal group as it seems. Nice hint!

{
  "type": "state",
  "common": {
    "name": "setPointTemperature",
    "type": "number",
    "role": "level.temperature",
    "unit": "°C",
    "read": true,
    "write": true
  },
  "native": {
    "id": [
      "1434c972-f05f-475e-94a7-608c0bb909fe",
      "8d9c910a-0a33-4c30-8e68-89607a19ed30"
    ],
    "step": 0.5,
    "debounce": 5000,
    "parameter": "setPointTemperature"
  },
  "from": "system.adapter.hmip.0",
  "user": "system.user.admin",
  "ts": 1641400299652,
  "_id": "hmip.0.devices.3014F711A000265BE989ABAA.channels.1.setPointTemperature",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

**Comment by Apollon77** [comment] 2022-01-06 18:49
Hm ... no idea what I could do ...

**Closed** 2022-02-19 22:06 UTC
Labels: question

**Comment by unstressable** [comment] 2023-01-22 13:59
Any news here?

Problem is still there with 1.20.0

`Request error: StatusCodeError: 400 - {"errorCode":"NOT_HEATING_GROUP"}`

**Comment by Rookiestyle** [comment] 2023-01-29 19:04
I faced this issue as well and solved it for me
My setup:  Multiple thermostats assigned to one room, window sensors and 

In the Homematic app it's no longer possible to change the temperature of one of those thermostats, only the room's temperature can be changed.

Similar in iobroker... In the thermostat 's `setPointTemperature` I could see it's linked to two IDs.
Both exist as folders in the adapter's groups section. One is classified as *HEATING* (subfolder *type*), the other as *INDOOR_CLIMATE*. The *HEATING* one has a `setPointTemperature` state as well and this one is working without warnings. I'm using it in my visualization now.

**Comment by unstressable** [comment] 2023-10-28 10:07
same issue here. I know, that using the datapoints that appears at the group folder should work.
Problem ist: I've got 6 devices and much more folders in group section.

Names are cryptic. How can I find the corresponding ones?

Isnt there a workaround to use the devices directly. I mean, it works for me, but there are still these warnings...

**Comment by Rookiestyle** [comment] 2023-10-29 18:37
> Names are cryptic. How can I find the corresponding ones?

That's what I tried to describe in  my previous post.

![image](https://github.com/iobroker-community-adapters/ioBroker.hmip/assets/36454520/2b46fd90-db04-401a-9d63-51d12b0da3b3)
![image](https://github.com/iobroker-community-adapters/ioBroker.hmip/assets/36454520/eb8f710c-2f65-4e2e-ac0c-d2a78a17eec1)

You'll find both id values in the `groups`section, take the one that has a `setPointTemperature` 



> I've got 6 devices and much more folders in group section.

Same here.
There is one for heating and one for climate control in my case... plus old groups created for rooms that no longer exist and that I need to cleanup

**Comment by DrEm8ee** [comment] 2024-10-06 15:15
I have the same problem, but as soon as I change it, it always resets to the original state after a restart. Any ideas?

**Comment by mcm1957** [comment] 2024-10-06 16:58
This issue has been CLOSED 2022 !
So do not expect any useful reaction here. I suggest to ask eitehr at forum (https://iobroker.net) - which will be faster if there is any discussion useful - or open a new issue if its most likely a bug.
